services:
  - type: web
    name: scanqueue-app
    env: python
    pythonVersion: "3.12.0"
    buildCommand: pip install --upgrade pip setuptools && pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0